name: "lint"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: "go install github.com/rhysd/actionlint/cmd/actionlint@latest"
      - run: "actionlint -color"
