# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
name: "ci"

on:
  workflow_call:
    inputs:
      cacheEnabled:
        type: boolean
        required: false
        default: true

env:
  NODE_ENV: "ci"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: asdf-vm/actions/install@v4
      - uses: pnpm/action-setup@v5

      - name: Get pnpm store directory
        if: inputs.cacheEnabled
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v5
        if: inputs.cacheEnabled
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: "pnpm install --frozen-lockfile"
      - run: "pnpm run typecheck"
      - run: "pnpm run lint"
      - run: "pnpm run test:coverage"
      - run: "pnpm run build"
