name: "node-release"

on:
  workflow_call:
    secrets:
      RELEASE_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.RELEASE_TOKEN }}
