# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
name: "ci"

on:
  workflow_call:
    inputs:
      gitAuthorName:
        type: string
        required: false
        default: "GitHub"
      gitAuthorEmail:
        type: string
        required: false
        # Got the email from here:
        # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
        default: "github-actions@github.com"
      releaseEnabled:
        type: boolean
        required: false
        default: true
    secrets:
      GitHubToken:
        required: true
      NPMToken:
        required: true

env:
  NODE_ENV: "ci"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: "pnpm install --frozen-lockfile"
      - run: "pnpm run typecheck"
      - run: "pnpm run lint"
      - run: "pnpm run test:coverage"
      - run: "pnpm run build"
  release:
    if: inputs.releaseEnabled && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - "test"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: volta-cli/action@v1
      - run: "pnpm install --frozen-lockfile --ignore-scripts"
      - run: "pnpm run release"
        env:
          # https://github.com/semantic-release/github#github-authentication
          GITHUB_TOKEN: ${{ secrets.GitHubToken }}
          # https://docs.npmjs.com/creating-and-viewing-access-tokens
          NPM_TOKEN: ${{ secrets.NPMToken }}
          GIT_AUTHOR_NAME: ${{ inputs.gitAuthorName }}
          GIT_AUTHOR_EMAIL: ${{ inputs.gitAuthorEmail }}
          GIT_COMMITTER_NAME: ${{ inputs.gitAuthorName }}
          GIT_COMMITTER_EMAIL: ${{ inputs.gitAuthorEmail }}
