# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
name: "ci"

on:
  workflow_call:
    inputs:
      gitAuthorName:
        type: string
        required: false
        default: "GitHub Actions"
      gitAuthorEmail:
        type: string
        required: false
        # https://github.community/t/github-actions-bot-email-address/17204/5
        default: "41898282+github-actions[bot]@users.noreply.github.com"
      releaseEnabled:
        type: boolean
        required: false
        default: true
    secrets:
      GitHubToken:
        required: true
      NPMToken:
        required: true

env:
  NODE_ENV: "ci"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run test:coverage
      - run: npm run build
  release:
    if: "${{ inputs.releaseEnabled }} && github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    needs:
      - "test"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: volta-cli/action@v1
      - run: "npm ci --ignore-scripts"
      - run: npm run release
        env:
          # https://github.com/semantic-release/github#github-authentication
          GITHUB_TOKEN: ${{ secrets.GitHubToken }}
          # https://docs.npmjs.com/creating-and-viewing-access-tokens
          NPM_TOKEN: ${{ secrets.NPMToken }}
          GIT_AUTHOR_NAME: ${{ inputs.gitAuthorName }}
          GIT_AUTHOR_EMAIL: ${{ inputs.gitAuthorEmail }}
          GIT_COMMITTER_NAME: ${{ inputs.gitAuthorName }}
          GIT_COMMITTER_EMAIL: ${{ inputs.gitAuthorEmail }}
