name: "node-release"

on:
  workflow_call:
    inputs:
      publishEnabled:
        type: boolean
        required: false
        default: true
    secrets:
      RELEASE_TOKEN:
        required: true
      NPM_TOKEN:
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.RELEASE_TOKEN }}

  publish:
    needs: release-please
    if: inputs.publishEnabled && needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: asdf-vm/actions/install@v4
      - uses: pnpm/action-setup@v5
      - run: "pnpm install --frozen-lockfile"
      - run: "pnpm run build"
      - run: "pnpm publish --no-git-checks"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
